import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisProvider from "@/components/layout/lenis";
import Header from "@/components/layout/header";

export const neueMontreal = localFont({
  src: [
    {
      path: "../public/assets/fonts/ppneuemontreal-thin.woff",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/ppneuemontreal-book.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/ppneuemontreal-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/ppneuemontreal-bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/assets/fonts/ppneuemontreal-italic.woff",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/assets/fonts/ppneuemontreal-semibolditalic.woff",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-neue-montreal",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Model portfolio",
  description: "Generated by Muhammad Faizan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${neueMontreal.variable} antialiased`}>
        <LenisProvider>
          <Header />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
